### ISSUE TITLE
Face authentication error

### ISSUE THREAD

**Issue by homeyjoenka** [gruijter/com.gruijter.facepp#11]
i can't add a face in the app i want then i get an error i have already created a new account new api created app reinstalled homey restart but nothing help i don't get a face i hope i can be added i want the app is promising![image](https://user-images.githubusercontent.com/61145850/92080254-855a9a80-edc1-11ea-8592-0bf7f2864503.png)

**Comment by gruijter** [comment]
Thx 4 creating an issue. I will try if I can reproduce your problem, but I have to find some time to do so. So please be patient. 

Can you copy/paste the full log here? (Not a screenschot because part of the log is missing)

**Comment by homeyjoenka** [comment]
2020-09-03 08:08:48 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-03 08:08:46 [log] Analyzing new image from app settings 
2020-09-03 08:08:37 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-03 08:08:36 [log] Analyzing new image from app settings 
2020-09-03 08:03:49 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-03 08:03:48 [log] Analyzing new image from app settings 
2020-09-03 07:59:24 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-03 07:59:24 [log] Analyzing new image from app settings 
2020-09-03 07:59:01 [log] Face++ is running... 
2020-09-03 07:59:01 [log] ready syncing face set with cloud 
2020-09-03 07:59:01 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-03 07:59:00 [log] Re-initing app now 
2020-09-03 07:59:00 [log] logfile saved 
2020-09-03 07:59:00 [log] API Key settings changed, reloading app now 
2020-09-03 07:58:41 [log] No API key entered in app settings 
2020-09-03 07:58:41 [log] Re-initing app now 
2020-09-03 07:58:41 [log] logfile saved 
2020-09-03 07:58:41 [log] API Key settings changed, reloading app now 
2020-09-02 19:44:13 [log] Face++ is running... 
2020-09-02 19:44:13 [log] ready syncing face set with cloud 
2020-09-02 19:44:13 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-02 19:44:12 [log] capturing stderr 
2020-09-02 19:44:12 [log] capturing stdout 
2020-09-02 19:12:34 [log] app unload called 
2020-09-02 19:12:34 [log] logfile saved 
2020-09-02 19:12:33 [log] app unload called 
2020-09-02 19:11:53 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-02 19:11:52 [log] Analyzing new image from app settings 
2020-09-02 19:11:32 [log] Face++ is running... 
2020-09-02 19:11:32 [log] ready syncing face set with cloud 
2020-09-02 19:11:32 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-09-02 19:11:30 [log] Re-initing app now 
2020-09-02 19:11:30 [log] logfile saved 
2020-09-02 19:11:30 [log] API Key settings changed, reloading app now 
2020-09-02 13:40:23 [log] No API key entered in app settings 
2020-09-02 13:40:23 [log] capturing stderr 
2020-09-02 13:40:23 [log] capturing stdout

**Comment by homeyjoenka** [comment]
I have patience if it only works once I hope it would be very nice

**Comment by gruijter** [comment]
OK, I have tried to reproduce your issue. But for me everything works like it should.

- Are you sure you followed the steps as described in the app?
- Are you 100% sure that you entered the API key and secret FULLY and without additional characters?
- You did try to setup a completely new account with https://console.faceplusplus.com/ ?

This is what I did:

* De-installed the app
* Installed the face++ app from the Homey app store
* Went to app settings
* Created a new account
* Created a new API Key and secret (free use)
* Copied and pasted the key and secret into the Face++ app settings tab
* Saved the settings
* Saved the threshold level (unchanged at 70)
* Went to the add faces tab and added a jpg
* Face was added as intended

**Comment by homeyjoenka** [comment]
Hi 
We have all do it wat you have do it, can i senD you are privé Message that you control my token, or maybe senD you mij e-mail adres voor make i account something maybe i do wrong working

**Comment by Oooklart** [comment]
I have the same problem 
![Screenshot_20200911_213734](https://user-images.githubusercontent.com/37779210/92966026-10e5c280-f477-11ea-8776-ded53adcaceb.jpg)

**Comment by gruijter** [comment]
For @homeyjoenka it was solved by entering the api key via a pc in stead of via iphone. But actually @tranceblast your error is completely different. Econreset means you have a connection problem. So you have bad wifi or bad internet.

**Comment by Oooklart** [comment]
> For @homeyjoenka it was solved by entering the api key via a pc in stead of via iphone. But actually @tranceblast your error is completely different. Econreset means you have a connection problem. So you have bad wifi or bad internet.

Thanks, it is solved now. It was the wifi connection.
