### ISSUE TITLE
AUTHENTICATION_ERROR

### ISSUE THREAD

**Issue by jahnkenneth** [gruijter/com.gruijter.facepp#12]
I am getting the following error:

2020-12-08 15:15:57 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-08 15:15:55 [log] Analyzing new image from app settings 
2020-12-08 15:15:34 [log] Face++ is running... 
2020-12-08 15:15:34 [log] ready syncing face set with cloud 
2020-12-08 15:15:34 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-08 15:15:33 [log] capturing stderr 
2020-12-08 15:15:33 [log] capturing stdout 
2020-12-08 15:15:26 [log] app unload called 
2020-12-08 15:15:26 [log] logfile saved 
2020-12-08 15:15:26 [log] app unload called 
2020-12-08 15:15:26 [log] logfile saved 
2020-12-08 15:15:26 [log] app unload called 
2020-12-08 15:14:36 [err] Error: AUTHENTICATION_ERROR at FacePP._makeRequest (/facepp.js:206:34) at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-08 15:14:34 [log] Analyzing new image from app settings 
2020-12-08 15:14:24 [log] logfile deleted 

Using a computer when entering api and key. 
Have tried reinstalling app, and also making a new account on Face++. 
100% sure that I have entered correct api keys.

**Comment by gruijter** [comment]
do you still have this issue?
